<?php
/**
 * ACF Field Groups
 *
 * @author		Nir Goldberg
 * @package		scoop-child/functions/acf
 * @version		1.7.15
 */
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * ACF register field groups
 *
 * @fieldgroup	Homepage
 * @fieldgroup	ACF Front-End Form
 * @fieldgroup	Questions & Answers
 * @fieldgroup	Posts Carousels
 * @fieldgroup	Ratings
 * @fieldgroup	Category Attributes
 * @fieldgroup	User Information
 * @fieldgroup	Slideshow Attributes
 * @fieldgroup	Gallery Attributes
 * @fieldgroup	Attachment Attributes
 * @fieldgroup	Header/Footer Settings
 * @fieldgroup	My Siddur Settings
 * @fieldgroup	General Settings
 * @fieldgroup	ACF Form Fields
 */
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5ea00e8495c1a',
	'title' => __('Homepage', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5ea0186a73ce8',
			'label' => __('Main Template Layouts', 'kulam-scoop'),
			'name' => 'acf-main_template_layouts',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5ea018948eb7f' => array(
					'key' => '5ea018948eb7f',
					'name' => 'banner',
					'label' => __('Banner', 'kulam-scoop'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ea01d6a3c22a',
							'label' => __('Slides', 'kulam-scoop'),
							'name' => 'slides',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5ea01e253c22c',
							'min' => 1,
							'max' => 0,
							'layout' => 'row',
							'button_label' => __('Add Slide', 'kulam-scoop'),
							'sub_fields' => array(
								array(
									'key' => 'field_5ea01e253c22c',
									'label' => __('Title', 'kulam-scoop'),
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array(
									'key' => 'field_5ecb794b49a0d',
									'label' => __('Title Font Attributes', 'kulam-scoop'),
									'name' => 'title_font_attributes',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5ecbb886147b1',
											'label' => __('Override Defaults', 'kulam-scoop'),
											'name' => 'override_defaults',
											'type' => 'true_false',
											'instructions' => __('Override default font attributes for this particular slide', 'kulam-scoop'),
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'message' => '',
											'default_value' => 0,
											'ui' => 0,
											'ui_on_text' => '',
											'ui_off_text' => '',
										),
										array(
											'key' => 'field_5ecb799649a0f',
											'label' => __('Font Family', 'kulam-scoop'),
											'name' => 'font_family',
											'type' => 'font_family',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ecbb886147b1',
														'operator' => '==',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'font_family' => 0,
										),
										array(
											'key' => 'field_5ecb79dc49a10',
											'label' => __('Font Size', 'kulam-scoop'),
											'name' => 'font_size',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ecbb886147b1',
														'operator' => '==',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => 75,
											'placeholder' => '',
											'prepend' => '',
											'append' => 'px',
											'min' => 8,
											'max' => 100,
											'step' => 1,
										),
										array(
											'key' => 'field_5ecb7bec49a11',
											'label' => __('Font Weight', 'kulam-scoop'),
											'name' => 'font_weight',
											'type' => 'select',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ecbb886147b1',
														'operator' => '==',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'normal' => __('Normal', 'kulam-scoop'),
												'bold' => __('Bold', 'kulam-scoop'),
												100 => __('100', 'kulam-scoop'),
												200 => __('200', 'kulam-scoop'),
												300 => __('300', 'kulam-scoop'),
												400 => __('400', 'kulam-scoop'),
												500 => __('500', 'kulam-scoop'),
												600 => __('600', 'kulam-scoop'),
												700 => __('700', 'kulam-scoop'),
												800 => __('800', 'kulam-scoop'),
												900 => __('900', 'kulam-scoop'),
											),
											'default_value' => array(
												0 => 'normal',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'return_format' => 'value',
											'ajax' => 0,
											'placeholder' => '',
										),
										array(
											'key' => 'field_5ecbb9bab8b18',
											'label' => __('Top Margin', 'kulam-scoop'),
											'name' => 'top_margin',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ecbb886147b1',
														'operator' => '==',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => 150,
											'placeholder' => '',
											'prepend' => '',
											'append' => 'px',
											'min' => 0,
											'max' => 200,
											'step' => 1,
										),
									),
								),
								array(
									'key' => 'field_5ea01e4f3c22d',
									'label' => __('Short Description', 'kulam-scoop'),
									'name' => 'short_description',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => 'br',
								),
								array(
									'key' => 'field_5ea01e6c3c22e',
									'label' => __('Description', 'kulam-scoop'),
									'name' => 'description',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => '',
									'new_lines' => 'br',
								),
								array(
									'key' => 'field_5ec3524ee8b18',
									'label' => __('Link', 'kulam-scoop'),
									'name' => 'link',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ec35277e8b19',
									'label' => __('Link Target', 'kulam-scoop'),
									'name' => 'link_target',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'self' => __('Same window', 'kulam-scoop'),
										'blank' => __('New window', 'kulam-scoop'),
									),
									'default_value' => array(
										0 => 'self',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ea01fc73c230',
									'label' => __('Text Color', 'kulam-scoop'),
									'name' => 'text_color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#FFFFFF',
								),
								array(
									'key' => 'field_5ea01f973c22f',
									'label' => __('Background Image', 'kulam-scoop'),
									'name' => 'background_image',
									'type' => 'image',
									'instructions' => __('Image dimensions: 767x577 (px)', 'kulam-scoop'),
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5ea01dee3c22b',
									'label' => __('Image', 'kulam-scoop'),
									'name' => 'image',
									'type' => 'image',
									'instructions' => __('Image dimensions: 767x577 (px)', 'kulam-scoop'),
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'jpg,jpeg',
								),
							),
						),
						array(
							'key' => 'field_5ecbb035f1e0f',
							'label' => __('Title Font Attributes', 'kulam-scoop'),
							'name' => 'title_font_attributes',
							'type' => 'group',
							'instructions' => __('Default font attributes for slides titles. These attributes may be overridden in a slide level', 'kulam-scoop'),
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5ecbb108f1e10',
									'label' => __('Font Family', 'kulam-scoop'),
									'name' => 'font_family',
									'type' => 'font_family',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'font_family' => 0,
								),
								array(
									'key' => 'field_5ecbb10cf1e11',
									'label' => __('Font Size', 'kulam-scoop'),
									'name' => 'font_size',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 75,
									'placeholder' => '',
									'prepend' => '',
									'append' => 'px',
									'min' => 8,
									'max' => 100,
									'step' => 1,
								),
								array(
									'key' => 'field_5ecbb110f1e12',
									'label' => __('Font Weight', 'kulam-scoop'),
									'name' => 'font_weight',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'normal' => __('Normal', 'kulam-scoop'),
										'bold' => __('Bold', 'kulam-scoop'),
										100 => __('100', 'kulam-scoop'),
										200 => __('200', 'kulam-scoop'),
										300 => __('300', 'kulam-scoop'),
										400 => __('400', 'kulam-scoop'),
										500 => __('500', 'kulam-scoop'),
										600 => __('600', 'kulam-scoop'),
										700 => __('700', 'kulam-scoop'),
										800 => __('800', 'kulam-scoop'),
										900 => __('900', 'kulam-scoop'),
									),
									'default_value' => array(
										0 => 'normal',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ecbb9471f4b4',
									'label' => __('Top Margin', 'kulam-scoop'),
									'name' => 'top_margin',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 150,
									'placeholder' => '',
									'prepend' => '',
									'append' => 'px',
									'min' => 0,
									'max' => 200,
									'step' => 1,
								),
							),
						),
						array(
							'key' => 'field_5ea6f8aa7427c',
							'label' => __('Top Padding', 'kulam-scoop'),
							'name' => 'top_padding',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5ea6f8f67427d',
							'label' => __('Bottom Padding', 'kulam-scoop'),
							'name' => 'bottom_padding',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
					),
					'min' => '0',
					'max' => '1',
				),
				'layout_5ea018bb73ce9' => array(
					'key' => 'layout_5ea018bb73ce9',
					'name' => 'links_strip',
					'label' => __('Links Strip', 'kulam-scoop'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ea6f4ac74276',
							'label' => __('Links', 'kulam-scoop'),
							'name' => 'links',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5ea6f66274278',
							'min' => 3,
							'max' => 3,
							'layout' => 'row',
							'button_label' => __('Add Link', 'kulam-scoop'),
							'sub_fields' => array(
								array(
									'key' => 'field_5ea6f66274278',
									'label' => __('Main Title', 'kulam-scoop'),
									'name' => 'main_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array(
									'key' => 'field_5ea6f68474279',
									'label' => __('Sub Title', 'kulam-scoop'),
									'name' => 'sub_title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'readonly' => 0,
									'disabled' => 0,
								),
								array(
									'key' => 'field_5ea6f6a37427a',
									'label' => __('Link', 'kulam-scoop'),
									'name' => 'link',
									'type' => 'url',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ea6f6b57427b',
									'label' => __('Target', 'kulam-scoop'),
									'name' => 'target',
									'type' => 'select',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'self' => __('Same window', 'kulam-scoop'),
										'blank' => __('New window', 'kulam-scoop'),
									),
									'default_value' => array(
										0 => 'self',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ea6f54674277',
									'label' => __('Image', 'kulam-scoop'),
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'jpg,jpeg,png',
								),
							),
						),
						array(
							'key' => 'field_5ea6f93d2e792',
							'label' => __('Top Padding', 'kulam-scoop'),
							'name' => 'top_padding',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5ea6f9412e793',
							'label' => __('Bottom Padding', 'kulam-scoop'),
							'name' => 'bottom_padding',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
					),
					'min' => '0',
					'max' => '1',
				),
				'layout_5ea018d573cea' => array(
					'key' => 'layout_5ea018d573cea',
					'name' => 'links_boxes',
					'label' => __('Links Boxes', 'kulam-scoop'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ea839a6c6d18',
							'label' => __('Links', 'kulam-scoop'),
							'name' => 'links',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => 'field_5ea83b90c6d19',
							'min' => 2,
							'max' => 2,
							'layout' => 'row',
							'button_label' => __('Add Link', 'kulam-scoop'),
							'sub_fields' => array(
								array(
									'key' => 'field_5ea83b90c6d19',
									'label' => __('Title', 'kulam-scoop'),
									'name' => 'title',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'new_lines' => 'br',
								),
								array(
									'key' => 'field_5ea83bfbc6d1a',
									'label' => __('Link', 'kulam-scoop'),
									'name' => 'link',
									'type' => 'url',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ea83c01c6d1b',
									'label' => __('Target', 'kulam-scoop'),
									'name' => 'target',
									'type' => 'select',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'self' => __('Same window', 'kulam-scoop'),
										'blank' => __('New window', 'kulam-scoop'),
									),
									'default_value' => array(
										0 => 'self',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ea83c08c6d1c',
									'label' => __('Image', 'kulam-scoop'),
									'name' => 'image',
									'type' => 'image',
									'instructions' => __('Image dimensions: 767x530 (px)', 'kulam-scoop'),
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => 'jpg,jpeg,png',
								),
								array(
									'key' => 'field_5ea95be0fab65',
									'label' => __('Left Margin', 'kulam-scoop'),
									'name' => 'left_margin',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_5ea95bf5fab66',
											'label' => __('Desktop', 'kulam-scoop'),
											'name' => 'desktop',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '%',
											'min' => -20,
											'max' => 20,
											'step' => '0.1',
										),
										array(
											'key' => 'field_5ea95c1efab67',
											'label' => __('Mobile', 'kulam-scoop'),
											'name' => 'mobile',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '%',
											'min' => -20,
											'max' => 20,
											'step' => '0.1',
										),
									),
								),
								array(
									'key' => 'field_5ea95c4dfab68',
									'label' => __('Right Margin', 'kulam-scoop'),
									'name' => 'right_margin',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'table',
									'sub_fields' => array(
										array(
											'key' => 'field_5ea95c4dfab69',
											'label' => __('Desktop', 'kulam-scoop'),
											'name' => 'desktop',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '%',
											'min' => -20,
											'max' => 20,
											'step' => '0.1',
										),
										array(
											'key' => 'field_5ea95c4dfab6a',
											'label' => __('Mobile', 'kulam-scoop'),
											'name' => 'mobile',
											'type' => 'number',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '%',
											'min' => -20,
											'max' => 20,
											'step' => '0.1',
										),
									),
								),
							),
						),
						array(
							'key' => 'field_5ea6f96b2e794',
							'label' => __('Top Padding', 'kulam-scoop'),
							'name' => 'top_padding',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5ea6f96e2e795',
							'label' => __('Bottom Padding', 'kulam-scoop'),
							'name' => 'bottom_padding',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
					),
					'min' => '0',
					'max' => '1',
				),
			),
			'button_label' => __('Add Layout', 'kulam-scoop'),
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/main.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5a4fc58481113',
	'title' => __('ACF Front-End Form', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5a4fc5849fdd9',
			'label' => __('Display Front-End Form', 'kulam-scoop'),
			'name' => 'display_acf_form',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => __('Display Front-End Form', 'kulam-scoop'),
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5a4fdd3871d9b',
			'label' => __('ACF Form', 'kulam-scoop'),
			'name' => 'acf_form',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a4fc5849fdd9',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'upload' => __('upload', 'kulam-scoop'),
				'user_profile' => __('user_profile', 'kulam-scoop'),
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e86337963c2a',
			'label' => __('Form Title', 'kulam-scoop'),
			'name' => 'acf-form_form_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a4fdd3871d9b',
						'operator' => '==',
						'value' => 'upload',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8633af63c2b',
			'label' => __('Form Content Title', 'kulam-scoop'),
			'name' => 'acf-form_form_content_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a4fdd3871d9b',
						'operator' => '==',
						'value' => 'upload',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e8668eea69b5',
			'label' => __('Form Category Title', 'kulam-scoop'),
			'name' => 'acf-form_form_category_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a4fdd3871d9b',
						'operator' => '==',
						'value' => 'upload',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e89d267bf10c',
	'title' => __('Questions & Answers', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5e89d71b14535',
			'label' => __('Q&A Blocks', 'kulam-scoop'),
			'name' => 'acf-qna_blocks',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5e89dcc4363e7',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => __('Add Q&A Block', 'kulam-scoop'),
			'sub_fields' => array(
				array(
					'key' => 'field_5e89d2e914534',
					'label' => __('ID', 'kulam-scoop'),
					'name' => 'acf-qna_block_id',
					'type' => 'text',
					'instructions' => __('Use this field as a slug for your shortcode, e.g. [kulam_qna id=ID]', 'kulam-scoop'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e89dcc4363e7',
					'label' => __('Shortcode', 'kulam-scoop'),
					'name' => 'acf-qna_block_shortcode',
					'type' => 'text',
					'instructions' => __('Auto generated after post save/update.
Copy and paste this code into your post editor', 'kulam-scoop'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 1,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5e89d8d8911bd',
					'label' => __('Questions', 'kulam-scoop'),
					'name' => 'acf-qna_block_questions',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5e89d75914536',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => __('Add Question', 'kulam-scoop'),
					'sub_fields' => array(
						array(
							'key' => 'field_5e89d75914536',
							'label' => __('Question', 'kulam-scoop'),
							'name' => 'question',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5e89d77214537',
							'label' => __('Answer', 'kulam-scoop'),
							'name' => 'answer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ea9a4102841b',
	'title' => __('Posts Carousels', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5ea9a4a182caa',
			'label' => __('Carousels', 'kulam-scoop'),
			'name' => 'acf-pc_carousels',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5ea9a59882cac',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => __('Add Carousel', 'kulam-scoop'),
			'sub_fields' => array(
				array(
					'key' => 'field_5ea9a52782cab',
					'label' => __('ID', 'kulam-scoop'),
					'name' => 'id',
					'type' => 'text',
					'instructions' => __('Use this field as a slug for your shortcode, e.g. [kulam_pc id=ID]', 'kulam-scoop'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5ea9a59882cac',
					'label' => __('Shortcode', 'kulam-scoop'),
					'name' => 'shortcode',
					'type' => 'text',
					'instructions' => __('Auto generated after post save/update.
Copy and paste this code into your post editor', 'kulam-scoop'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 1,
					'disabled' => 0,
				),
				array(
					'key' => 'field_5ea9a5cd82cad',
					'label' => __('Posts Categories', 'kulam-scoop'),
					'name' => 'posts_categories',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'category',
					'field_type' => 'checkbox',
					'add_term' => 0,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
					'allow_null' => 0,
				),
				array(
					'key' => 'field_5eaab16026d52',
					'label' => __('Number of Posts', 'kulam-scoop'),
					'name' => 'number_of_posts',
					'type' => 'number',
					'instructions' => __('Select 0 to show all posts', 'kulam-scoop'),
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 0,
					'max' => '',
					'step' => 1,
				),
				array(
					'key' => 'field_5ea9a63982cae',
					'label' => __('Title', 'kulam-scoop'),
					'name' => 'title',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ea9a6fa82caf',
							'label' => __('Title', 'kulam-scoop'),
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array(
							'key' => 'field_5ea9a71f82cb0',
							'label' => __('Font Family', 'kulam-scoop'),
							'name' => 'font_family',
							'type' => 'font_family',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'font_family' => 0,
						),
						array(
							'key' => 'field_5ea9a74a82cb1',
							'label' => __('Font Size', 'kulam-scoop'),
							'name' => 'font_size',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 20,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 8,
							'max' => 72,
							'step' => 1,
						),
						array(
							'key' => 'field_5ec5667997556',
							'label' => __('Font Weight', 'kulam-scoop'),
							'name' => 'font_weight',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'normal' => __('Normal', 'kulam-scoop'),
								'bold' => __('Bold', 'kulam-scoop'),
								100 => __('100', 'kulam-scoop'),
								200 => __('200', 'kulam-scoop'),
								300 => __('300', 'kulam-scoop'),
								400 => __('400', 'kulam-scoop'),
								500 => __('500', 'kulam-scoop'),
								600 => __('600', 'kulam-scoop'),
								700 => __('700', 'kulam-scoop'),
								800 => __('800', 'kulam-scoop'),
								900 => __('900', 'kulam-scoop'),
							),
							'default_value' => array(
								0 => 'normal',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ea9a78d82cb2',
							'label' => __('Color', 'kulam-scoop'),
							'name' => 'color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5ec5698297557',
							'label' => __('Background Color', 'kulam-scoop'),
							'name' => 'background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5ea9a7bd82cb3',
							'label' => __('Background Image', 'kulam-scoop'),
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5ec3530d73172',
							'label' => __('Link', 'kulam-scoop'),
							'name' => 'link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_5ec582b253bec',
					'label' => __('Slide Title', 'kulam-scoop'),
					'name' => 'slide_title',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ec582d453bed',
							'label' => __('Font Family', 'kulam-scoop'),
							'name' => 'font_family',
							'type' => 'font_family',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'font_family' => 0,
						),
						array(
							'key' => 'field_5ec582d753bee',
							'label' => __('Font Size', 'kulam-scoop'),
							'name' => 'font_size',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 20,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 8,
							'max' => 72,
							'step' => 1,
						),
						array(
							'key' => 'field_5ec582db53bef',
							'label' => __('Font Weight', 'kulam-scoop'),
							'name' => 'font_weight',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'normal' => __('Normal', 'kulam-scoop'),
								'bold' => __('Bold', 'kulam-scoop'),
								100 => __('100', 'kulam-scoop'),
								200 => __('200', 'kulam-scoop'),
								300 => __('300', 'kulam-scoop'),
								400 => __('400', 'kulam-scoop'),
								500 => __('500', 'kulam-scoop'),
								600 => __('600', 'kulam-scoop'),
								700 => __('700', 'kulam-scoop'),
								800 => __('800', 'kulam-scoop'),
								900 => __('900', 'kulam-scoop'),
							),
							'default_value' => array(
								0 => 'normal',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5ec582de53bf0',
							'label' => __('Color', 'kulam-scoop'),
							'name' => 'color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5ea9a87d82cb6',
							'label' => __('Background Image', 'kulam-scoop'),
							'name' => 'background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array(
					'key' => 'field_5ea9a7f282cb4',
					'label' => __('General', 'kulam-scoop'),
					'name' => 'general',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ea9a83c82cb5',
							'label' => __('Scheme Color', 'kulam-scoop'),
							'name' => 'scheme_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
					),
				),
				array(
					'key' => 'field_5eaaf13c21b4b',
					'label' => __('Carousel Options', 'kulam-scoop'),
					'name' => 'carousel_options',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5eaaf15321b4c',
							'label' => __('Slide Width', 'kulam-scoop'),
							'name' => 'slide_width',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 200,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5eaaf1b121b4d',
							'label' => __('Slide Height', 'kulam-scoop'),
							'name' => 'slide_height',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 200,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5eaaf1e121b4f',
							'label' => __('Slide Margin', 'kulam-scoop'),
							'name' => 'slide_margin',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 10,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5eaaf1ff21b50',
							'label' => __('Minimum Slides', 'kulam-scoop'),
							'name' => 'minimum_slides',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5eaaf22a21b51',
							'label' => __('Maximum Slides', 'kulam-scoop'),
							'name' => 'maximum_slides',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 3,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5eaaf25e21b53',
							'label' => __('Move Slides', 'kulam-scoop'),
							'name' => 'move_slides',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => 1,
							'max' => '',
							'step' => 1,
						),
						array(
							'key' => 'field_5eaaf2c321b54',
							'label' => __('Navigation', 'kulam-scoop'),
							'name' => 'navigation',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								0 => __('Arrows', 'kulam-scoop'),
								'bullets' => __('Bullets', 'kulam-scoop'),
								'both' => __('Both', 'kulam-scoop'),
								'none' => __('None', 'kulam-scoop'),
							),
							'default_value' => array(
								0 => 0,
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5eaaf33721b55',
							'label' => __('Transition Speed', 'kulam-scoop'),
							'name' => 'transition_speed',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 100,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'ms',
							'min' => 0,
							'max' => '',
							'step' => 10,
						),
						array(
							'key' => 'field_5eaaf38b21b56',
							'label' => __('Slide Duration', 'kulam-scoop'),
							'name' => 'slide_duration',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 10000,
							'placeholder' => '',
							'prepend' => '',
							'append' => 'ms',
							'min' => 0,
							'max' => '',
							'step' => 10,
						),
						array(
							'key' => 'field_5eaaf3e121b58',
							'label' => __('Auto Play', 'kulam-scoop'),
							'name' => 'auto_play',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								0 => __('On', 'kulam-scoop'),
								'off' => __('Off', 'kulam-scoop'),
							),
							'default_value' => array(
								0 => 0,
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5eaaf46d21b5a',
							'label' => __('Auto Pause Hover', 'kulam-scoop'),
							'name' => 'auto_pause_hover',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								0 => __('On', 'kulam-scoop'),
								'off' => __('Off', 'kulam-scoop'),
							),
							'default_value' => array(
								0 => 0,
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5c4f03398b667',
	'title' => __('Ratings', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5c4f027d245b5',
			'label' => __('דירוג', 'kulam-scoop'),
			'name' => 'range',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5c4f0299245b6',
					'label' => __('שם דירוג', 'kulam-scoop'),
					'name' => 'range_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5c4f030cb353a',
			'label' => __('ratings', 'kulam-scoop'),
			'name' => 'range_en',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5c4f0329b353b',
					'label' => __('rating name', 'kulam-scoop'),
					'name' => 'range_name_en',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5a37e01e4f32b',
	'title' => __('Category Attributes', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5ec0d7520984b',
			'label' => __('Google Map', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e931b1afeed3',
			'label' => __('Google Map', 'kulam-scoop'),
			'name' => 'acf-category_google_map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array(
			'key' => 'field_5ec0d55809848',
			'label' => __('Popup', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ec0e0da71d07',
			'label' => __('Image', 'kulam-scoop'),
			'name' => 'acf-category_popup_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5ec0e12771d08',
			'label' => __('Button Text', 'kulam-scoop'),
			'name' => 'acf-category_popup_button_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5ec0e16e71d09',
			'label' => __('Button Text Color', 'kulam-scoop'),
			'name' => 'acf-category_popup_button_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ec0e1c771d0a',
			'label' => __('Button Background Color', 'kulam-scoop'),
			'name' => 'acf-category_popup_button_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ec0d5ba09849',
			'label' => __('General', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d024ba641baa',
			'label' => __('Background Image', 'kulam-scoop'),
			'name' => 'acf-category_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5ec0e00d230ae',
			'label' => __('Content', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 1,
		),
		array(
			'key' => 'field_5cf314117dac4',
			'label' => __('Post Types', 'kulam-scoop'),
			'name' => 'acf-category_post_types',
			'type' => 'taxonomy',
			'instructions' => __('Leave this field empty to display default Post Types', 'kulam-scoop'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_types_tax',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'category',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5820857489fcb',
	'title' => __('User Information', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5820857820158',
			'label' => __('Profile', 'kulam-scoop'),
			'name' => 'profile',
			'type' => 'textarea',
			'instructions' => __('Tell us something about yourself!', 'kulam-scoop'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_582085a620159',
			'label' => __('Gender', 'kulam-scoop'),
			'name' => 'gender',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Female' => __('Female', 'kulam-scoop'),
				'Male' => __('Male', 'kulam-scoop'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_582085f22015a',
			'label' => __('Date of Birth', 'kulam-scoop'),
			'name' => 'date_of_birth',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'edit',
			),
			array(
				'param' => 'current_user',
				'operator' => '==',
				'value' => 'logged_in',
			),
		),
	),
	'menu_order' => 7,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e98230787054',
	'title' => __('Slideshow Attributes', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5e982fd03ae7e',
			'label' => __('Shortcode', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e982fa13ae7d',
			'label' => __('Shortcode', 'kulam-scoop'),
			'name' => 'acf-slideshow_shortcode',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5e98249d32ac1',
			'label' => __('Title', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e98234232abd',
			'label' => __('Title', 'kulam-scoop'),
			'name' => 'acf-slideshow_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5e9823af32abf',
			'label' => __('Font Family', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_font_family',
			'type' => 'font_family',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'font_family' => 0,
		),
		array(
			'key' => 'field_5e9823da32ac0',
			'label' => __('Font Size', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_font_size',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 20,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 8,
			'max' => 72,
			'step' => 1,
		),
		array(
			'key' => 'field_5ec571b37531c',
			'label' => __('Font Weight', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_font_weight',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'normal' => __('Normal', 'kulam-scoop'),
				'bold' => __('Bold', 'kulam-scoop'),
				100 => __('100', 'kulam-scoop'),
				200 => __('200', 'kulam-scoop'),
				300 => __('300', 'kulam-scoop'),
				400 => __('400', 'kulam-scoop'),
				500 => __('500', 'kulam-scoop'),
				600 => __('600', 'kulam-scoop'),
				700 => __('700', 'kulam-scoop'),
				800 => __('800', 'kulam-scoop'),
				900 => __('900', 'kulam-scoop'),
			),
			'default_value' => array(
				0 => 'normal',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e9824d632ac2',
			'label' => __('Color', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5ec571ba7531d',
			'label' => __('Background Color', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5e98255d401ff',
			'label' => __('Background Image', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5ec35348f5029',
			'label' => __('Link', 'kulam-scoop'),
			'name' => 'acf-slideshow_title_link',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ec58196cfde8',
			'label' => __('Slide Title', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ec581f8cfde9',
			'label' => __('Font Family', 'kulam-scoop'),
			'name' => 'acf-slideshow_slider_title_font_family',
			'type' => 'font_family',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'font_family' => 0,
		),
		array(
			'key' => 'field_5ec581fccfdea',
			'label' => __('Font Size', 'kulam-scoop'),
			'name' => 'acf-slideshow_slider_title_font_size',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 20,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 8,
			'max' => 72,
			'step' => 1,
		),
		array(
			'key' => 'field_5ec58202cfdeb',
			'label' => __('Font Weight', 'kulam-scoop'),
			'name' => 'acf-slideshow_slider_title_font_weight',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'normal' => __('Normal', 'kulam-scoop'),
				'bold' => __('Bold', 'kulam-scoop'),
				100 => __('100', 'kulam-scoop'),
				200 => __('200', 'kulam-scoop'),
				300 => __('300', 'kulam-scoop'),
				400 => __('400', 'kulam-scoop'),
				500 => __('500', 'kulam-scoop'),
				600 => __('600', 'kulam-scoop'),
				700 => __('700', 'kulam-scoop'),
				800 => __('800', 'kulam-scoop'),
				900 => __('900', 'kulam-scoop'),
			),
			'default_value' => array(
				0 => 'normal',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5ec5820dcfdec',
			'label' => __('Color', 'kulam-scoop'),
			'name' => 'acf-slideshow_slider_title_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5e987e42d38eb',
			'label' => __('Background Image', 'kulam-scoop'),
			'name' => 'acf-slideshow_slider_title_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5e98259640200',
			'label' => __('General', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e98235932abe',
			'label' => __('Scheme Color', 'kulam-scoop'),
			'name' => 'acf-slideshow_scheme_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'pojo_slideshow',
			),
		),
	),
	'menu_order' => 8,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5eb90fcf9398a',
	'title' => __('Gallery Attributes', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5eb9395cb6329',
			'label' => __('Title', 'kulam-scoop'),
			'name' => 'acf-gallery_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5eb910214bcd6',
			'label' => __('Date', 'kulam-scoop'),
			'name' => 'acf-gallery_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd.m.Y',
			'return_format' => 'd.m.Y',
			'first_day' => 0,
		),
		array(
			'key' => 'field_5eb910b43985b',
			'label' => __('Description', 'kulam-scoop'),
			'name' => 'acf-gallery_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_5eb94bc5ac415',
			'label' => __('Scheme Color', 'kulam-scoop'),
			'name' => 'acf-gallery_scheme_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5eb910f03985c',
			'label' => __('Images', 'kulam-scoop'),
			'name' => 'acf-gallery_images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'jpg,jpeg',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'gallery',
			),
		),
	),
	'menu_order' => 9,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5eb961ab57a1c',
	'title' => __('Attachment Attributes', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5eb9638fc2c0c',
			'label' => __('Date', 'kulam-scoop'),
			'name' => 'acf-attachment_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd.m.Y',
			'return_format' => 'd.m.Y',
			'first_day' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'attachment',
				'operator' => '==',
				'value' => 'image',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e4beda225c07',
	'title' => __('Header/Footer Settings', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5e890348f6c87',
			'label' => __('Search Form', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e4bf3a29323d',
			'label' => __('Search Form Type', 'kulam-scoop'),
			'name' => 'acf-option_search_form_type',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'minimalist' => __('Minimalist', 'kulam-scoop'),
				'exposed' => __('Exposed', 'kulam-scoop'),
			),
			'default_value' => array(
				0 => 'minimalist',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5e8902e5f6c86',
			'label' => __('Search Input Placeholder', 'kulam-scoop'),
			'name' => 'acf-option_search_input_placeholder',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e890285f6c85',
			'label' => __('Advanced Search', 'kulam-scoop'),
			'name' => 'acf-option_advanced_search',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5eb0f6c571e08',
			'label' => __('Contact Details', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5eb0fc7a85b13',
			'label' => __('Email', 'kulam-scoop'),
			'name' => 'acf-option_contact_details_email',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5eb0fca485b14',
			'label' => __('Address', 'kulam-scoop'),
			'name' => 'acf-option_contact_details_address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5eb0fcf585b15',
			'label' => __('Phone', 'kulam-scoop'),
			'name' => 'acf-option_contact_details_phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5eb0fd2d85b16',
			'label' => __('Social Networks', 'kulam-scoop'),
			'name' => 'acf-option_contact_details_social_networks',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5eb0fd5a85b17',
					'label' => __('Youtube', 'kulam-scoop'),
					'name' => 'youtube',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5eb0fd7685b18',
					'label' => __('Facebook', 'kulam-scoop'),
					'name' => 'facebook',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5eb0fd9985b19',
					'label' => __('Instagram', 'kulam-scoop'),
					'name' => 'instagram',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-header-footer',
			),
		),
	),
	'menu_order' => 101,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5ceaa42a7cfb6',
	'title' => __('My Siddur Settings', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5a7fbe646768d',
			'label' => __('Custom Label', 'kulam-scoop'),
			'name' => 'acf-option_my_siddur_custom_label',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-my-siddur',
			),
		),
	),
	'menu_order' => 102,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5a40e3bb6d57d',
	'title' => __('General Settings', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5d6cbdbcddbb1',
			'label' => __('Homepage', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d6cbdd6ddbb2',
			'label' => __('Categories in Row', 'kulam-scoop'),
			'name' => 'acf-option_homepage_categories_in_row',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 4,
			'min' => 4,
			'max' => 6,
			'step' => 1,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5d6d5b6e9011b',
			'label' => __('My Siddur Tile Background Image', 'kulam-scoop'),
			'name' => 'acf-option_my_siddur_tile_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5d6d5bca9011c',
			'label' => __('Upload Tile Background Image', 'kulam-scoop'),
			'name' => 'acf-option_upload_tile_background_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5d028ffc43370',
			'label' => __('Category Attributes', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a71c0fb1a7c2',
			'label' => __('Category Page Post Types', 'kulam-scoop'),
			'name' => 'acf-option_category_page_post_types',
			'type' => 'taxonomy',
			'instructions' => __('Default selected Post Types to be displayed in a category page.
Additional Post Types may be added and re-sorted per each category', 'kulam-scoop'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'post_types_tax',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
		),
		array(
			'key' => 'field_5e4b96e5aa1b6',
			'label' => __('Category Description Toggling', 'kulam-scoop'),
			'name' => 'acf-option_category_description_toggling',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e9393cd97e12',
			'label' => __('Google Maps API', 'kulam-scoop'),
			'name' => 'acf-option_google_maps_api',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5ca5f481de29b',
			'label' => __('Subcategory Attributes', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5ca5f4c7de29c',
			'label' => __('Background color', 'kulam-scoop'),
			'name' => 'acf-option_subcategory_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#8F95CE',
		),
		array(
			'key' => 'field_5ca5f6cdde29d',
			'label' => __('Font Color', 'kulam-scoop'),
			'name' => 'acf-option_subcategory_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FFFFFF',
		),
		array(
			'key' => 'field_5e8c4b80e2ff2',
			'label' => __('Questions & Answers', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5e8d7f3b4ad72',
			'label' => __('Font Family', 'kulam-scoop'),
			'name' => 'acf-option_qna_font_family',
			'type' => 'font_family',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'font_family' => 0,
		),
		array(
			'key' => 'field_5e8dcb0641bb6',
			'label' => __('Font Size', 'kulam-scoop'),
			'name' => 'acf-option_qna_font_size',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 20,
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => 8,
			'max' => 72,
			'step' => 1,
		),
		array(
			'key' => 'field_5e8c4baae2ff3',
			'label' => __('Color', 'kulam-scoop'),
			'name' => 'acf-option_qna_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5cd11da3dcb13',
			'label' => __('Social', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cd11dcadcb14',
			'label' => __('Google Analytics Code', 'kulam-scoop'),
			'name' => 'acf-option_google_analytics_code',
			'type' => 'text',
			'instructions' => __('Code format: UA-XXXXXXXXX-X', 'kulam-scoop'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5e4ba10303d95',
			'label' => __('Google Tag Manager Code', 'kulam-scoop'),
			'name' => 'acf-option_google_tag_manager_code',
			'type' => 'text',
			'instructions' => __('Code format: GTM-XXXXXX', 'kulam-scoop'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ca5febcbad83',
			'label' => __('Misc', 'kulam-scoop'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d63767651bc8',
			'label' => __('Enable Activity Types custom taxonomy', 'kulam-scoop'),
			'name' => 'acf-option_enable_activity_types_custom_taxonomy',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d6d6e5390f33',
			'label' => __('Enable Audiences custom taxonomy', 'kulam-scoop'),
			'name' => 'acf-option_enable_audiences_custom_taxonomy',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5e74a985c5ba1',
			'label' => __('Strip Image', 'kulam-scoop'),
			'name' => 'acf-option_strip_image',
			'type' => 'image',
			'instructions' => __('Default strip which will be displayed in single post, page and category.
Image dimensions: 1140x268 (px)', 'kulam-scoop'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-general',
			),
		),
	),
	'menu_order' => 103,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5e865fad1f3c4',
	'title' => __('ACF Form Fields', 'kulam-scoop'),
	'fields' => array(
		array(
			'key' => 'field_5e86605e1140b',
			'label' => __('Category', 'kulam-scoop'),
			'name' => 'acf-form_category',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'field_type' => 'select',
			'allow_null' => 0,
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-general',
			),
		),
	),
	'menu_order' => 104,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

endif;